# POST http://192.168.0.3:3000/api/auth/register
# Content-Type: application/json

# {
# "email":"arismoratalla@gmail.com",
# "password":"12345678",
# "firstName":"Aris",
# "lastName":"Moratalla",
# "role":"admin"
# }

# POST http://192.168.0.3:3000/api/hrmis/inAM
# Content-Type: application/json

# POST http://172.16.110.78:3000/api/hrmis/inAM
# POST http://192.168.0.3:3000/api/hrmis/outAM
# Content-Type: application/json

# {
# "employee_num":"jaa-0615"
# }

# POST http://157.230.245.80:3001/api/hrmis/outAM
# GET https://node-server.dost9.ph/api/hrmis/earlybirds
# http://172.16.110.78:3000/api/auth/getWhitelistedIps
# Content-Type: application/json

# POST https://192.168.1.8:3000/api/hrmis/inPM
# POST https://node-server.dost9.ph/api/hrmis/outPM
# Content-Type: application/json

# {
# "employee_num":"RBG-0110"
# }
# GET http://localhost:3000/api/dms/login
# Content-Type: application/json

GET https://node-server.dost9.ph/api/dms/login
Content-Type: application/json
